Phase04/csharp
Star-Academy/Team8-Codes pull request #3
Opened 2020-08-09 12:12 UTC by intenvy

C Sharp Basic Project added

2020-08-09 13:38 UTC, mostmand commented on .vscode/settings.json
> +{
بهتره کلا فولدر 
.vscode
رو
ignore
کنید

2020-08-09 13:38 UTC, mostmand commented on students/utils/JsonHandler.cs
> +            if (File.Exists(filePath))
[https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html](https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html)

در واقع میشه  این جوری نوشتش:
```csharp
if (!File.Exists(filePath))
{
    throw new IOException("File not found!");
}

var text = File.ReadAllText(filePath);
return JsonSerializer.Deserialize<List<T>>(text);
```

2020-08-09 13:38 UTC, mostmand commented on students/utils/JsonHandler.cs
> +            if (File.Exists(filePath))
از کلمه کلیدی
var
هم می‌تونید استفاده کنید همین طوری که در این مثال من استفاده کردم

2020-08-09 13:38 UTC, mostmand commented on students/utils/JsonHandler.cs
> +        public static List<T> retrieveModels(string filePath)
توی سی‌شارپ
naming convention
با جاوا فرق داره و اسم توابع هم مثل اسم کلاس‌ها
PascalCase
هست یعنی حرف اولش هم بزرگه

2020-08-09 13:38 UTC, mostmand commented on students/students.csproj
> +    <PackageReference Include="System.Text.Json" Version="5.0.0-preview.7.20364.11" />
از نسخه‌ی
preview
استفاده شده که البته الان اوکیه ولی توی پروژه‌های واقعی باید از ورژن‌های نهایی استفاده کرد

2020-08-09 13:38 UTC, mostmand commented on students/Program.cs
> +            var list = scores.GroupJoin(
قسمت محاسبه ی معدل می‌تونه یه تابع جدا بشه و از قسمت پرینت اون جدا بشه

2020-08-09 13:53 UTC, mahdimalverdi requested changes

2020-08-09 13:53 UTC, mahdimalverdi commented on students/Program.cs
> +            var list = scores.GroupJoin(
بچه ها اینجا به جای اینکه گروپ جوین رو روی scores بزنید روی students بزنید

یعنی چی؟

یعنی شما می گید هر دانشجو یک سری نمره داره 

و بعد به راحتی می تونید گروپ بای و سلکت بعدی رو حذف کنید 

یه همچین حالتی

students
.GroupJoin(scores,
student => student.StudentNumber,
scoreRecord => scoreRecord.StudentNumber,
( student, scoreRecords) =>{
 new StudentReport() {
 FirstName = student.FirstName,
LastName = student.LastName,
Avg = scoreRecords.Average(s => s.Score)
}
})
.OrderByDescending(studentReport => studentReport.Average)
                .Take(count);

2020-08-09 16:34 UTC, hbehboudi commented on students/Program.cs
> +                .Take(count);
در کل میتونید متغیرهای مختلف (با اسم‌های مناسب) بسازید و با استفاده از اونا توابع 
linq 
رو از هم جدا کنید.
یا حتی میشه براشون توابع جداگانه ساخت.
اینجوری خوانایی کد خیلی بیشتر میشه.

2020-08-10 13:08 UTC, MahdiHma reviewed
سلام. خدا قوت و خسته نباشید.
نکات مهم را دوستان گفته بودند. 
بجز موارد ذکر شده مورد دیگری نبود. کد بصورت کلی خوب و خوانا بود (بجز قسمت استفاده از لاندا اکسپرشن).

2020-08-11 14:43 UTC, intenvy commented on students/utils/JsonHandler.cs
> +            if (File.Exists(filePath))
Done

2020-08-11 14:43 UTC, intenvy commented on students/utils/JsonHandler.cs
> +        public static List<T> retrieveModels(string filePath)
done

2020-08-11 14:52 UTC, BijanEisapour commented on students/utils/JsonHandler.cs
> +        public static List<T> retrieveModels(string filePath)
به ورژن نهایی 4.7.2 تغییر داده شد

2020-08-11 14:53 UTC, BijanEisapour commented on students/students.csproj
> +    <PackageReference Include="System.Text.Json" Version="5.0.0-preview.7.20364.11" />
<p dir='rtl' align='right'>
به ورژن نهایی 4.7.2 تغییر داده شد
</p>

2020-08-11 16:07 UTC, BijanEisapour commented on students/Program.cs
> +            var list = scores.GroupJoin(
<p dir='rtl' align='right'>
خیلی ممنون
<br>
اصلاح شد
</p>

2020-08-11 16:11 UTC, BijanEisapour commented on students/Program.cs
> +                .Take(count);
<p dir='rtl' align='right'>
بله کاملاً درسته
<br>
اصلاح شد
</p>

2020-08-11 17:03 UTC, mostmand approved these changes

2020-08-12 08:57 UTC, mahdimalverdi approved these changes

2020-08-12 08:57 UTC, mahdimalverdi commented on School/models/StudentReport.cs
> +            return string.Format("StudentReport({0} {1}: {2})", FirstName, LastName, Average);
از قابلیت جدید سی شارپ استفاده کنید

$"{FirstName} {LastName} {Average}"

2020-08-12 09:28 UTC, hbehboudi approved these changes

2020-08-12 09:40 UTC, BijanEisapour commented on School/models/StudentReport.cs
> +            return string.Format("StudentReport({0} {1}: {2})", FirstName, LastName, Average);
<p dir='rtl' align='right'>
اصلاح شد
</p>

2020-08-12 09:52 UTC, FarshidNooshi approved these changes
سلام 
خسته نباشید 
کد به صورت کلی خوانا و مرتب شده بود و همچنین مطالب اصلی رو هم دوستان اشاره کرده بودند.
موفق باشید.

2020-08-12 13:12 UTC, merged