Phase05/google sharp
Star-Academy/Team8-Codes pull request #5
Opened 2020-08-11 14:34 UTC by BijanEisapour

Implemented main project using C#

2020-08-11 15:30 UTC, mostmand commented on GoogleSharp/GoogleSharp/src/core/query/Terms.cs
> +            pattern.Matches(expression).OfType<Match>().ToList().ForEach(
فراخوانی تابع
`ToList()`
پیش از 
`ForEach()`
اضافه است و باعث می‌شود دو بار
iteration
انجام شود چرا که کوئری های
Linq
به صورت
Lazy Evaluation
هستند.

2020-08-11 15:30 UTC, mostmand commented on GoogleSharp/GoogleSharp/src/core/structures/Token.cs
> +        private static String Normalize(string key)
در سی‌شارپ بهتر است از
string
به جای
String
استفاده شود

2020-08-11 15:30 UTC, mostmand commented on GoogleSharp/GoogleSharp/src/core/structures/Token.cs
> +        private string key;
اگر این
Field
تغییر نمی کند و فقط در کانستراکتور مقداردهی می‌شود می‌توانید آن را
readonly
تعریف کنید.

2020-08-11 15:30 UTC, mostmand commented on GoogleSharp/GoogleSharp/src/utils/FileHandler.cs
> +            .OfType<Match>().ToList().ForEach(match => { tokens.Add(new Token(match.Groups[0].Value)); });
این جا هم فراخوانی تابع
`ToList()`
اضافه است.

2020-08-11 15:30 UTC, mostmand commented on GoogleSharp/GoogleSharp/src/utils/Prettifier.cs
> +            List<T> itemList = new List<T>(inputSet);
از کلمه کلیدی
var
بیش‌تر استفاده کنید.

2020-08-11 15:30 UTC, mostmand commented on GoogleSharp/GoogleSharp/src/utils/Prettifier.cs
> +            List<T> itemList = new List<T>(inputSet);
هم‌چنین می‌توانید از متد
`ToList()`
استفاده کنید.

2020-08-11 15:57 UTC, ahmadsalimi approved these changes

2020-08-11 15:57 UTC, ahmadsalimi commented on GoogleSharp/GoogleSharp.Test/Tests/src/core/engine/QueryEngineTests.cs
> +                FileHandler.GetDocumentsFromFolder("../../../Tests/resources/input")
Declare a constant field for path.

2020-08-11 15:57 UTC, ahmadsalimi commented on GoogleSharp/GoogleSharp.Test/Tests/src/core/structures/TokenTests.cs
> +        }
<div dir="rtl">

احسنت!

</div>

2020-08-11 15:57 UTC, ahmadsalimi commented on GoogleSharp/GoogleSharp/src/core/engine/InvertedIndex.cs
> +            foreach (Document doc in documents)
<div dir="rtl">

کلا همه‌جا به جای explicit type از var استفاده کنید.

</div>

2020-08-11 15:57 UTC, ahmadsalimi commented on GoogleSharp/GoogleSharp/src/core/query/Terms.cs
> +            pattern.Matches(expression).OfType<Match>().ToList().ForEach(
<div dir="rtl">

البته کلا تابع ForEach روی List تعریف میشه و روی IEnumerable کار نمی‌کنه. ولی به هر جهت کلا لزومی نداره از این مدل foreach استفاده کنیم، همون foreach معمولی بهتره وقتی صرفا IEnumerable داریم.

</div>

2020-08-12 09:23 UTC, mahdimalverdi requested changes

2020-08-12 09:23 UTC, mahdimalverdi commented on GoogleSharp/GoogleSharp.Test/Tests/src/core/engine/GoogleInvertedIndexTests.cs
> +            var expected = new Dictionary<Token, HashSet<Document>>(){
آیا امکان ماک شدن برای داکیومنت وجود نداشت؟

2020-08-12 09:23 UTC, mahdimalverdi commented on GoogleSharp/GoogleSharp/src/core/query/ExcTerms.cs
> +        private readonly Regex PATTERN = new Regex(@"\-(\w+)", RegexOptions.Compiled | RegexOptions.IgnoreCase);
static تعریف شود که فقط یک بار کامپایل شود

2020-08-12 09:23 UTC, mahdimalverdi commented on GoogleSharp/GoogleSharp/src/core/query/AndTerms.cs
> +        private readonly Regex PATTERN = new Regex(@"( *[^\+\-\w]|^)(\w+)", RegexOptions.Compiled | RegexOptions.IgnoreCase);
استاتیک تعریف شود

2020-08-12 09:23 UTC, mahdimalverdi commented on GoogleSharp/GoogleSharp/src/core/query/OrTerms.cs
> +        private readonly Regex PATTERN = new Regex(@"\+(\w+)", RegexOptions.Compiled | RegexOptions.IgnoreCase);
استاتیک

2020-08-12 09:23 UTC, mahdimalverdi commented on GoogleSharp/GoogleSharp/src/core/query/OrTerms.cs
> +            this.Tokens.ForEach(token => results.UnionWith(index.GetDocumentsOfToken(token)));
```CSharp
var results = this.Tokens.SelectMany(token => index.GetDocumentsOfToken(token)).ToHashSet();
```

2020-08-12 09:23 UTC, mahdimalverdi commented on GoogleSharp/GoogleSharp/src/core/structures/Token.cs
> +            if (obj == null || GetType() != obj.GetType())
```CSharp
 if(obj is Token other)
 {
  return this.Key == other.Key;
 }
 return false;
```

2020-08-12 09:23 UTC, mahdimalverdi commented on GoogleSharp/GoogleSharp/src/core/structures/Token.cs
> +            if (that != null)
```CSharp
if(obj is Token that)
```

2020-08-12 09:23 UTC, mahdimalverdi commented on GoogleSharp/GoogleSharp/src/utils/FileHandler.cs
> +            Regex regex = new Regex(@"[A-Za-z0-9]+", RegexOptions.Compiled | RegexOptions.IgnoreCase);
یک متغییر استاتیک در کلاس شود

2020-08-12 09:23 UTC, mahdimalverdi commented on GoogleSharp/GoogleSharp/src/utils/Prettifier.cs
> +        public const int MAX_ITEMS = 8;
قوانین نام گذاری کانست ها مرور شود باید پاسکال کیس نوشته شود

2020-08-12 09:23 UTC, mahdimalverdi commented on GoogleSharp/GoogleSharp/src/utils/Prettifier.cs
> +            int maxSize = ("" + itemList.Count).Length;
```CSharp
itemList.Count.ToString().Length
```

2020-08-12 09:23 UTC, mahdimalverdi commented on GoogleSharp/GoogleSharp/src/utils/Prettifier.cs
> +                builder.Append("\t" + LeftPad("" + (idx + 1), maxSize) + ") " + itemList[idx] + "\n");
```CSharp
$"\t{ LeftPad("" + (idx + 1), maxSize) }) { itemList[idx]}\n"
```

2020-08-12 10:16 UTC, BijanEisapour commented on GoogleSharp/GoogleSharp/src/utils/Prettifier.cs
> +        public const int MAX_ITEMS = 8;
<p dir='rtl' align='right'>
ممنون
<br>
نمیدونستیم با Java فرق داره
<br>
اصلاح شد
</p>

2020-08-12 13:26 UTC, BijanEisapour commented on GoogleSharp/GoogleSharp/src/core/structures/Token.cs
> +            if (obj == null || GetType() != obj.GetType())
<p dir='rtl' align='right'>
عالی بود
</p>

2020-08-12 15:46 UTC, ahmadsalimi commented on GoogleSharp/GoogleSharp/src/core/structures/Token.cs
> +            if (obj == null || GetType() != obj.GetType())
```CSharp
return obj is Token other && this.key == other.key;
```

2020-08-12 15:48 UTC, ahmadsalimi commented on GoogleSharp/GoogleSharp/src/utils/Prettifier.cs
> +            int maxSize = ("" + itemList.Count).Length;
به جای این که استرینگش کنیم اینجوری بهتر نیست؟
```CSharp
itemList.Count / 10 + 1
```

2020-08-12 20:17 UTC, mahdimalverdi commented on GoogleSharp/GoogleSharp/src/utils/Prettifier.cs
> +            int maxSize = ("" + itemList.Count).Length;
log10 بگیری یه چیزی ولی این :)

2020-08-12 21:16 UTC, hbehboudi approved these changes
خیلی خیلی عالی بود.
دمتون گرم.

2020-08-12 21:16 UTC, hbehboudi commented on GoogleSharp/GoogleSharp/src/core/engine/GoogleInvertedIndex.cs
> +            return result == null ? new HashSet<Document>() : result;
برای سادگی میتونید به این صورت بنویسید
```csharp
return result ?? new HashSet<Document>();
```

2020-08-12 21:16 UTC, hbehboudi commented on GoogleSharp/GoogleSharp.Test/Tests/src/utils/FileHandlerTests.cs
> +            expected.Add(new Document("doc3.txt", "dummyPath/doc3.txt"));
اینجا هم میتونید از
Collection Initializers
استفاده کنید.
تابع بعدی هم همینطور

2020-08-12 21:16 UTC, hbehboudi commented on GoogleSharp/GoogleSharp/src/core/engine/GoogleInvertedIndex.cs
> +                this.Index[token].Add(doc);
کلا جاهای زیادی از
this
استفاده کردید که لازم نبوده.
میتونید برای سادگی بیشتر اونایی که لازم نیست رو حذف کنید.

2020-08-12 21:16 UTC, hbehboudi commented on GoogleSharp/GoogleSharp/src/core/engine/GoogleInvertedIndex.cs
> +        public HashSet<Document> GetDocumentsOfToken(Token token)
معمولا توابع 
public
رو قبل از توابع 
private
قرار میدن. البته خیلی مهم نیست.

2020-08-13 06:54 UTC, BijanEisapour commented on GoogleSharp/GoogleSharp/src/utils/Prettifier.cs
> +            int maxSize = ("" + itemList.Count).Length;
<p dir='rtl' align='right'>
نه قطعاً 
<br>
چون اگه تعداد 999 باشه ما دنبال 3 ئیم ولی چیزی که شما میگی 100 میشه
</p>

2020-08-13 06:56 UTC, BijanEisapour commented on GoogleSharp/GoogleSharp/src/core/engine/GoogleInvertedIndex.cs
> +            return result == null ? new HashSet<Document>() : result;
<p dir='rtl' align='right'>
خیلی جالب بود
<br>
ممنون
</p>

2020-08-13 08:20 UTC, mahdimalverdi approved these changes

2020-08-15 10:10 UTC, Parsa2820 reviewed
تست ها خیلی کامل بودن. خسته نباشید.

2020-08-15 10:10 UTC, Parsa2820 commented on GoogleSharp/GoogleSharp/src/utils/FileHandler.cs
> +            foreach (var match in Pattern.Matches (fileContent).OfType<Match> ())
<p dir="rtl">
به نظرم از curly bracket استفاده بشه بهتره
</p>

2020-08-15 10:10 UTC, Parsa2820 commented on GoogleSharp/GoogleSharp/src/core/structures/Token.cs
> +        public string Key {
<p dir="rtl">
وقتی Property داره چرا Field تعریف کردید؟
</p>

2020-08-15 10:10 UTC, Parsa2820 commented on GoogleSharp/GoogleSharp/src/core/engine/QueryEngine.cs
> +            results.UnionWith (query.Ands.GetResults (index)); // + AND results
<p dir="rtl">
فکر کنم results اشتراکش با AND باید گرفته بشه.
</p>

2020-08-15 10:10 UTC, Parsa2820 commented on GoogleSharp/GoogleSharp/src/core/engine/GoogleInvertedIndex.cs
> +                IndexDocument (doc, handler);
<p dir="rtl">
اینجا هم curly bracket باشه خوانا تره.
</p>

2020-08-15 10:52 UTC, BijanEisapour commented on GoogleSharp/GoogleSharp/src/core/structures/Token.cs
> +        public string Key {
<p dir='rtl' align='right'>
چون داخل getter و setter به اون فیلد احتیاج داشتیم
</p>

2020-08-15 10:54 UTC, BijanEisapour commented on GoogleSharp/GoogleSharp/src/core/engine/QueryEngine.cs
> +            results.UnionWith (query.Ands.GetResults (index)); // + AND results
<p dir='rtl' align='right'>
جوری که ما به پروژه نگاه کردیم این بود که اول تمام صفحاتی که کلمات and دارن جمع‌آوری شن
<br>
بعد صفحاتی که کلمات or دارن بهش اضافه شن
<br>
و در نهایت صفحاتی که کلمات exc دارن ازش کم شن
<br>
برای همین اجتماع گرفتیم چون هدف اضافه کردن نتایج بود

</p>

2020-08-15 11:04 UTC, merged