Phase08/bagherzadeh
Star-Academy/Team8-Codes pull request #7
Opened 2020-08-24 10:45 UTC by intenvy

Added Nest client to search engine!

2020-08-24 12:19 UTC, mohammadhheidarzade approved these changes
آقا دوست داشتم کدتون رو
دمتون گرم
عالی =))))))

2020-08-24 12:19 UTC, mohammadhheidarzade commented on Bagherzadeh/BagherEngine/App/SearchEngineApp.cs
> +            WriteLine($"Welcome to {AppName}! Copyright(c) Team8 {Year} {Version}");
راضیم ازتون=))))))))))))))))))
عالی

2020-08-24 12:19 UTC, mohammadhheidarzade commented on Bagherzadeh/BagherEngine/App/SearchEngineApp.cs
> +                    break;
عالی 
عالی

2020-08-24 12:19 UTC, mohammadhheidarzade commented on Bagherzadeh/BagherEngine/Elastic/Engine.cs
> +        }
اینو بخونید حتما
https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/bool-dsl-complex-query-usage.html

2020-08-24 12:19 UTC, mohammadhheidarzade commented on Bagherzadeh/BagherEngine/Elastic/Validator.cs
> +                throw new ElasticApiException(error.Message);
اینجوری اگه برنامه به خودیو خود کرش هم نکنه با نوشتن این حتما کرش میکنه
و تابع های بالایی به همین شکل...

2020-08-24 12:19 UTC, mohammadhheidarzade commented on Bagherzadeh/BagherEngine/Program.cs
> +
این حذف بشه بهتره :)

2020-08-24 13:42 UTC, mostmand commented
باقرزاده چیه قضیه‌اش؟🤦‍♂️

2020-08-24 13:52 UTC, mostmand commented on Bagherzadeh/BagherEngine/Elastic/Engine.cs
> +                Must = query.Ands.Tokens.Select(token => (QueryContainer) new MatchQuery { Field = "content", Query = token.Key }).ToList(),
"content"
رو به صورت
const
تعریف کنید

2020-08-24 13:52 UTC, mostmand commented on Bagherzadeh/BagherEngine/Program.cs
> +        importer.Import(documents, "bagher-documents", ids);
چرا
ids
به طور جداگانه پاس داده میشه در حالی که توی خود
documentها
هست؟

2020-08-24 13:52 UTC, mostmand commented on Bagherzadeh/BagherEngine/QuerySystem/Query.cs
> +        public AndTerms Ands { get; set; }
propertyهای
Ands, Ors, Excs
می‌تونن از تایپ کلاس پدر یعنی
Terms
تعریف بشن

2020-08-24 13:52 UTC, mostmand commented on Bagherzadeh/BagherEngine/text.txt
> +4. Elastic/Importer
این به نظر یادداشت شخصی میاد!

2020-08-25 06:49 UTC, Parsa2820 approved these changes
خیلی خوبه. خسته نباشید

2020-08-25 07:13 UTC, hassanzaker commented on Bagherzadeh/BagherEngine/Utils/FileHandler.cs
> +            return files.Select(f => new Document(Path.GetFileName(f), GetFileContent(f))).ToList();
بنظرم حالا که امدین تابع 
GetFileContent
اگه بجاش یه تابع بزنین که ورودیش 
f
 و خروجیش 
Document 
 باشه و اگه اونجا  داکیومنت را
new
کنین بهتره

2020-08-25 07:14 UTC, hassanzaker approved these changes
در کل انقدر خوب زدین نمیشه چیزی گفت. 
خسته نباشید

2020-08-25 12:35 UTC, ahmadsalimi commented on Bagherzadeh/BagherEngine/Elastic/IndexDefiner.cs
> +        }
```CSharp
private readonly IElasticClient client = ElasticClientFactory.CreateElasticClient();
```

2020-08-25 12:35 UTC, ahmadsalimi commented on Bagherzadeh/BagherEngine/Models/Token.cs
> +            return false;
```CSharp
return obj is Token other && Key == other.Key;
```

2020-08-26 11:03 UTC, mahdimalverdi requested changes

2020-08-26 11:03 UTC, mahdimalverdi commented on Bagherzadeh/BagherEngine/App/App.cs
> +            var app = new SearchEngineApp("Resources/Documents");
استرینگ به متغیر کانست تبدیل  بشه

2020-08-26 11:03 UTC, mahdimalverdi commented on Bagherzadeh/BagherEngine/App/ConsoleApp.cs
> +            firstSpaceIndex = input.IndexOf(' ');
کاراکتر Sapce درون یک متغییر ریخته بشه

2020-08-26 11:03 UTC, mahdimalverdi commented on Bagherzadeh/BagherEngine/App/ConsoleApp.cs
> +                arguments = "";
از String.Empty() استفاده بشه

2020-08-26 11:03 UTC, mahdimalverdi commented on Bagherzadeh/BagherEngine/App/SearchEngineApp.cs
> +                WriteLine("No keywords passed!");
متغییر کانست

2020-08-26 11:03 UTC, mahdimalverdi commented on Bagherzadeh/BagherEngine/App/SearchEngineApp.cs
> +            WriteLine(FileHandler.GetFileContent(ResourcesDirectory + "/" + arguments));
از Path.Combine() استفاده شود

2020-08-26 11:03 UTC, mahdimalverdi commented on Bagherzadeh/BagherEngine/App/SearchEngineApp.cs
> +            WriteLine("search <terms> -- view <documentId> -- help");
کانست

2020-08-26 11:03 UTC, mahdimalverdi commented on Bagherzadeh/BagherEngine/Elastic/ElasticClientFactory.cs
> +            var uri = new Uri("http://localhost:9200");
کانست :)

2020-08-26 11:03 UTC, mahdimalverdi commented on Bagherzadeh/BagherEngine/Elastic/Engine.cs
> +            Enumerable.Range(0, hits.Length).ToList().ForEach(index => documents[index].Id = hits[index].Id);
این کار رو نکنید الکی دارید سر بار اضافه کنید
قشنگ از فور استفاده کنید

2020-08-27 09:19 UTC, hbehboudi approved these changes

2020-08-27 09:19 UTC, hbehboudi commented on Bagherzadeh/BagherEngine/Elastic/Engine.cs
> +                    MustNot = query.Excs.Tokens.Select(token => (QueryContainer) new MatchQuery { Field = "content", Query = token.Key }).ToList()
.ToList()
رو نیاز ندارن. بردارید بهتره

2020-08-27 09:19 UTC, hbehboudi commented on Bagherzadeh/BagherEngine/Elastic/Engine.cs
> +        }
اگه دوست داشتید توابع تک خطی رو میتونید به این شکل بنویسید.
```csharp
private static ISearchResponse<Document> SearchDocuments(QueryContainer queryContainer) =>
            client.Search<Document>(s => s
                .Index("bagher-documents")
                .Query(q => queryContainer)
                .Size(100)
            );
```

2020-08-27 09:19 UTC, hbehboudi commented on Bagherzadeh/BagherEngine/Elastic/Engine.cs
> +    public static class Engine
به جای استاتیک از سینگلتون استفاده کنید.
https://refactoring.guru/design-patterns/singleton/csharp/example

2020-08-27 09:19 UTC, hbehboudi commented on Bagherzadeh/BagherEngine/Elastic/Engine.cs
> +    public static class Engine
بقیه‌ی کلاس‌های استاتیک هم همینطور

2020-08-31 09:43 UTC, intenvy commented on Bagherzadeh/BagherEngine/Elastic/Validator.cs
> +                throw new ElasticApiException(error.Message);
ببین ما کلاس
validator
رو اصن گذاشتیم که اکسپشن پرتاب کنه و این اکسپشنا همگی در 
main
هندل میشن

2020-08-31 09:51 UTC, intenvy commented on Bagherzadeh/BagherEngine/Elastic/Engine.cs
> +        }
دستت درد نکنه

2020-08-31 10:02 UTC, intenvy commented on Bagherzadeh/BagherEngine/Program.cs
> +        importer.Import(documents, "bagher-documents", ids);
ایمپورتر یک کلاس جنریک است بنابراین چیز هایی که بهش پاس میدیم لزوما
id
در خودشون ندارن

2020-08-31 11:14 UTC, intenvy commented
> باقرزاده چیه قضیه‌اش؟🤦‍♂️
> @intenvy @BijanEisapour
گوگل یه عدده. باقرزاده هم یه عدد بود اگه یادتون باشه توو فیلم سنپترزبورگ
=)))
یه عدد بین 7 و 8

2020-08-31 11:15 UTC, merged