Phase09/web backend
Star-Academy/Team8-Codes pull request #9
Opened 2020-09-02 14:31 UTC by intenvy

2020-09-03 19:01 UTC, ahmadsalimi approved these changes

2020-09-04 21:01 UTC, mostmand requested changes

2020-09-04 21:01 UTC, mostmand commented on BagherMusic/server/Controllers/ArtistController.cs
> +			this.searchService = searchService;
احسنت از
DependencyInjection
استفاده کردید
👌

2020-09-04 21:01 UTC, mostmand commented on BagherMusic/server/Controllers/ArtistController.cs
> +		private readonly ISearchEngineService searchService;
تب‌های 8 اسپیسی کم‌تر دیده بودم کسی استفاده کنه

2020-09-04 21:01 UTC, mostmand commented on BagherMusic/server/Controllers/ArtistController.cs
> +		/*
این کامنت لازم نیست

2020-09-04 21:01 UTC, mostmand commented on BagherMusic/server/Controllers/ArtistController.cs
> +					new { message = e.Message, StatusCode = 400, currentDate = DateTime.Now }
به جای عدد 400 از
https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=netcore-3.1
استفاده کنید

2020-09-04 21:01 UTC, mostmand commented on BagherMusic/server/Models/MusicNonGeneric.cs
> +			// General
به جای کامنت گذاشتن می‌تونید چند تا تابع داشته باشید مثلاً
InitializeMetadata()
InitializeArtists()
InitializeCoverArts()
و ...

2020-09-04 21:01 UTC, mostmand commented on BagherMusic/server/Services/ISearchEngineService.cs
> +		where T : IComparable
چرا
id
باید
comparable
باشد؟

2020-09-04 21:01 UTC, mostmand commented on BagherMusic/server/Services/ImportService.cs
> +			client = ElasticClientFactory.GetInstance();
می‌توانید
client
را هم در تابع سازنده
inject
کنید

2020-09-04 21:01 UTC, mostmand commented on BagherMusic/server/Services/SearchEngineService.cs
> +			if (!running)
چک کردن
runningتون
Thread-safe
نیست اگه چند تا ریکوئست هم‌زمان بیاد چند بار
RunService
کال میشه

2020-09-04 21:01 UTC, mostmand commented on BagherMusic/server/Services/SearchEngineService.cs
> +			if (!running)
هم چنین من متوجه نشدم چرا این جا
RunService
کال شده و توی تابع سازنده فراخوانی نشده
چون کارهایی که این تابع داره انجام میده به نظر میاد کارایی هست که معمولاً توی تابع سازنده انجام میشن

2020-09-04 21:01 UTC, mostmand commented on BagherMusic/server/Services/SearchEngineService.cs
> +		private Dictionary<Type, string> IndexNames = new Dictionary<Type, string>();
به نظرم این طرز استفاده از
type
قشنگ نیست
به نظرم به جای این که 
genericها
رو توی تابع‌هاتون داشته باشید توی اینترفیس
ISearchEngineService
داشته باشید و برای سرچ
Artist
و
Music
انواع مختلف این اینترفیس را
inject
کنید

2020-09-05 15:26 UTC, mahdimalverdi requested changes

2020-09-05 15:26 UTC, mahdimalverdi commented on BagherMusic/server/Controllers/ImportController.cs
> +				return new ObjectResult(
از BadRequest استفاده کنید

2020-09-05 15:26 UTC, mahdimalverdi commented on BagherMusic/server/Controllers/SearchController.cs
> +			try
از یک تابع پرایوت جنریک استفاده بکنید برای هر دو تابع درصد مشابهت زیادی دارند

2020-09-05 15:26 UTC, mahdimalverdi commented on BagherMusic/server/Core/QuerySystem/Terms.cs
> +		protected void Collect(string expression, Regex pattern, int regexGroupIndex)
به جای اینکه از طریق ورودی این تابع این موارد گرفته شود از طریق کانستراکتور هم میشه گرفت و حتی بهتره
فرض کنید بخواید یه تابع دیگه بهش اضافه کنید

2020-09-05 15:26 UTC, mahdimalverdi commented on BagherMusic/server/Core/Structures/ResultSet.cs
> +		public double Delay { get; set; }
آیا وجود Set لزومی داره؟

2020-09-05 15:26 UTC, mahdimalverdi commented on BagherMusic/server/Services/SearchEngineService.cs
> +			AcceptableFuzziness = Int32.Parse(_config["SearchService:SearchOptions:AcceptableFuzziness"]);
تبدیل به کانست بشن استرینگ ها

2020-09-06 11:44 UTC, intenvy commented on BagherMusic/server/Controllers/ArtistController.cs
> +		private readonly ISearchEngineService searchService;
مشکل گیت هاب هست

2020-09-10 13:12 UTC, merged